;;; vhdl-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vhdl-ts-mode.el

(autoload 'vhdl-ts-install-grammar "vhdl-ts-mode" "\
Install VHDL tree-sitter grammar.

This command requires Git, a C compiler and (sometimes) a C++ compiler,
and the linker to be installed and on PATH." t)
(autoload 'vhdl-ts-mode "vhdl-ts-mode" "\
Major mode for editing VHDL files, using tree-sitter library.

(fn)" t)
(register-definition-prefixes "vhdl-ts-mode" '("vhdl-ts-"))

;;; End of scraped data

(provide 'vhdl-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vhdl-ts-mode-autoloads.el ends here
