#+title: My Literate =.emacs.d=
#+author: Robb Enzmann
#+properties: header-args:elisp :tangle init-test.el

Want to use it? Go ahead!

#+begin_src shell
git clone https://github.com/renzmann/.emacs.d ~/.emacs.d
#+end_src

* Goals

I use all three of the major platforms, in both GUI and TTY mode.  So
this config is designed to work equally well for:

| platform | terminal | GUI | ssh + TTY | Tramp |
|----------+----------+-----+-----------+-------|
| Linux    | ✔        | ✔   | ✔         | ✔     |
| macOS    | ✔        | ✔   | ✔         | ✔     |
| Windows  | ❌       | ✔   | ❌        | ✔     |

Once I figure out how to get colors working in Windows terminal, I'll
update this table.  For now though, the 16 bit colors don't react to
my color theme, and so on Windows I rely singularly on GUI mode,
rather than WSL or emacs inside Alacritty.

* Tangling

My configuration is a single literate programming document, which is tangled into the standard =init.el= and supporting files.  This is so I can keep track of all the crazy things I try and explain them inline with the final code I decide to include.  Some platforms like GitHub can render this document in a limited way, but to see all the final configuration values I use you will likely have to view this document in Emacs itself.

* Packages

The initial cornerstone of every Emacs configuration is a decision on package management and configuration.  Since =use-package= will have built-in support in a future Emacs version, I'm going to use that along with the built-in =package.el=.  I don't have much reason other than the stability of them being built-in for choosing them.

On earlier Emacs (<29.1), to solve the "bootstrapping" problem of getting =use-package= into the repository, it's maintained as a subtree:

#+begin_src shell :results output drawer
subtree-use-package() {
    git subtree $1 \
        https://github.com/jwiegley/use-package master \
        --prefix=use-package \
        --squash
}

subtree-use-package add || subtree-use-package pull
#+end_src

Since this is a custom installation (i.e. not done through =package-install=), we need to make sure Emacs can see =use-package= and load it.

#+begin_src elisp
(eval-when-compile
  (add-to-list 'load-path (concat user-emacs-directory "use-package"))
  (require 'use-package))
#+end_src

#+RESULTS:
: use-package


* Keybindings
In the unlikely event that something below is loaded incorrectly and causes initialization to stop, I like to have my basic key command loaded early, especially so that navigating to the error can happen more quickly.



* Mode line
#+begin_src elisp
(setq column-number-mode t
      mode-line-in-non-selected-windows t)
#+end_src

#+RESULTS:
: t

* =eldoc=
I find it very distracting when =eldoc= suddenly pops up and consumes a large part of the screen for docstrings in python.

#+begin_src elisp
(setq eldoc-echo-area-use-multiline-p nil)
#+end_src

#+RESULTS:
: t

* Org-mode
#+begin_src elisp
(setq org-agenda-files '("~/.emacs.d/org/work.org")
      org-hugo-front-matter-format "yaml")
#+end_src

*
