#+TITLE: My =.emacs.d=
#+AUTHOR: Robb Enzmann

Want to use it? Go ahead! You can give it a try without affecting
any existing configuration like this:

#+begin_src shell :eval never
  git clone --recursive https://github.com/renzmann/.emacs.d ~/renzmann.emacs.d
  emacs --init-directory=~/renzmann.emacs.d
#+end_src

All external dependencies, except for Fonts, are explicitly
included under the =elpa/= directory, meaning it's as simple as
"clone-n-go". Getting a font you like is left to you.

* Getting Emacs
** Windows
I go to the [[https://alpha.gnu.org/gnu/emacs/pretest/windows/][pretest FTP]] to get the latest version of Emacs.
Usually not quite up-to-date with the master branch, but still
one version number ahead of the most recent official release on
the [[https://ftp.gnu.org/gnu/emacs/windows/][main FTP]].

** Mac
On macOS, I've had the best luck with [[https://github.com/jimeh/emacs-builds/releases][jimeh's nightly builds]].
These Emacs.app bundles have no external dependencies, signed
with a developer certificate, and notarized by Apple, so it
/just works/.

*** If Jimeh's build doesn't work
Some security updates from Apple can cause issues with native
compilation (notably 15.4.1). In that case, compile from source:

#+begin_src shell :eval never
  brew install \
    pkg-config texinfo libgccjit autoconf automake make \
    jansson gnutls mailutils imagemagick tree-sitter

  git clone git://git.savannah.gnu.org/emacs.git
  cd emacs
  ./autogen.sh
  ./configure \
      --prefix="${HOME}/.local" \
      --with-ns \
      --disable-ns-self-contained \
      --with-json \
      --with-tree-sitter \
      --without-native-compilation \
      --with-imagemagick \
      --with-mailutils \
      --without-compress-install
  gmake -j $(sysctl -n hw.ncpu)
  gmake install
#+end_src

** Linux
Often the system package manager version is out of date. Compile
from a release tarball. On Debian, install dev libraries first:

#+begin_src shell :eval never
  sudo apt-get install \
      autoconf automake build-essential curl \
      libgccjit-12-dev libgif-dev libgnutls28-dev \
      libgtk-4-dev libgtk2.0-dev libjpeg-dev \
      libncurses-dev libpng-dev libtiff-dev \
      libtree-sitter-dev libx11-dev libxpm-dev \
      make texinfo
#+end_src

Then build:

#+begin_src shell :eval never
  EMACS_VERSION=29.3
  curl -O https://ftp.gnu.org/gnu/emacs/emacs-${EMACS_VERSION}.tar.xz
  tar xf emacs-${EMACS_VERSION}.tar.xz
  cd emacs-${EMACS_VERSION}
  ./configure \
    --prefix=$HOME/.local \
    --with-native-compilation \
    --with-tree-sitter \
    --with-gnutls \
    --with-jpeg \
    --with-png \
    --with-rsvg \
    --with-tiff \
    --with-wide-int \
    --with-xft \
    --with-xml2 \
    --with-xpm \
    --without-dbus \
    --without-pop
  make -j
  make install
#+end_src

* Inspirations
- [[https://protesilaos.com/][Protesilaos Stavrou]]
- [[https://panadestein.github.io/emacsd/][Ramon Panadestein]]
- [[https://www.masteringemacs.org/][Mickey Petersen]]
- [[https://github.com/minad][Daniel Mendler]]
- [[https://github.com/oantolin][Omar Antolin Camarena]]
- [[https://www.lucacambiaghi.com/vanilla-emacs/readme.html][Luca's Literate Config]]
