#+title: My Literate =.emacs.d=
#+author: Robb Enzmann
#+properties: header-args:elisp :tangle init.el

Want to use it? Go ahead!

#+begin_src sh
git clone https://github.com/renzmann/.emacs.d ~/.emacs.d
#+end_src

* Goals

I use all three of the major platforms, in both GUI and TTY mode.  So
this config is designed to work equally well for:

| platform | terminal | GUI | ssh + TTY | Tramp |
|----------+----------+-----+-----------+-------|
| Linux    | ✔        | ✔   | ✔         | ✔     |
| macOS    | ✔        | ✔   | ✔         | ✔     |
| Windows  | ❌       | ✔   | ❌        | ✔     |

Once I figure out how to get colors working in Windows terminal, I'll
update this table.  For now though, the 16 bit colors don't react to
my color theme, and so on Windows I rely singularly on GUI mode,
rather than WSL or emacs inside Alacritty.

* Tangling

My configuration is a single literate programming document, which is tangled into the standard =init.el= and supporting files.  This is so I can keep track of all the crazy things I try and explain them inline with the final code I decide to include.  Some platforms like GitHub can render this document in a limited way, but to see all the final configuration values I use you will likely have to view this document in Emacs itself.

* Packages

To solve the "bootstrapping" problem of getting =use-package= into the repository, it's maintained as a subtree in its own directory.

#+begin_src shell
[ ! -d use-package ] && git subtree add https://github.com/jwiegley/use-package --prefix=use-package
#+end_src

#+RESULTS:

#+begin_src elisp
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
#+end_src

* Mode line
#+begin_src elisp
(setq column-number-mode t
      mode-line-in-non-selected-windows t)
#+end_src

* =eldoc=
#+begin_src elisp
(setq eldoc-echo-area-use-multiline-p nil)
#+end_src

* Org-mode
#+begin_src elisp
(setq org-agenda-files '("~/.emacs.d/org/work.org")
      org-hugo-front-matter-format "yaml")
#+end_src

*
