#+title: My Literate =.emacs.d=
#+author: Robb Enzmann
#+property: header-args:emacs-lisp :tangle init.el :comments link
#+OPTIONS: toc:2 num:nil

Want to use it? Go ahead!

#+begin_src shell
git clone https://github.com/renzmann/.emacs.d ~/.emacs.d
#+end_src

* Goals

I use all three of the major platforms, in both GUI and TTY mode.  So
this config is designed to work equally well for:

| platform | terminal | GUI | ssh + TTY | Tramp |
|----------+----------+-----+-----------+-------|
| Linux    | ✔        | ✔   | ✔         | ✔     |
| macOS    | ✔        | ✔   | ✔         | ✔     |
| Windows  | ❌       | ✔   | ❌        | ✔     |

Once I figure out how to get colors working in Windows terminal, I'll
update this table.  For now though, the 16 bit colors don't react to
my color theme, and so on Windows I rely singularly on GUI mode,
rather than WSL or emacs inside Alacritty.


* Tangling

My configuration is a single literate programming document, which is tangled into the standard =init.el= and supporting files.  This is so I can keep track of all the crazy things I try and explain them inline with the final code I decide to include.  Some platforms like GitHub can render this document in a limited way, but to see all the final configuration values I use you will likely have to view this document in Emacs itself.


* Header

To comply with the Emacs conventions for libraries, the tangled init.el must have the following [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][header]] and [[Footer][footer:]]

#+begin_src emacs-lisp :comments no
;;; init.el --- Robb's Emacs configuration -*- lexical-binding: t -*-

;; Copyright (C) 2020-2022 Robert Enzmann

;; Author: Robb Enzmann <robbenzmann@gmail.com>
;; Keywords: internal
;; URL: https://robbmann.io/

;;; Commentary:
;; A fully fledged, reproducible Emacs configuration

;;; Code:
#+end_src


* Custom

I prefer having custom modify its own file.  This next snippet ensures any =package-install= or =custom= edits go to =custom.el=.

#+begin_src emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file 'noerror))
#+end_src


* Packages

The initial cornerstone of every Emacs configuration is a decision on package management and configuration.  Since =use-package= will have built-in support in a future Emacs version, I'm going to use that along with the built-in =package.el=.  I don't have much reason other than the stability of them being built-in for choosing them.

#+begin_src emacs-lisp
(eval-when-compile
  (package-autoremove)
  (unless (package-installed-p 'use-package)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (package-refresh-contents)
    (package-install 'use-package))
  (require 'use-package))
#+end_src

#+RESULTS:
: use-package


* Theme
[[https://protesilaos.com/][Prot's]] themes have been reliably legible in nearly every situation.  Now with his new [[https://protesilaos.com/emacs/ef-themes][ef-themes]], they're pretty, too!  First, the =ef-themes-headings= variable will creates larger, bolder headings when in [[Org-mode]].

#+begin_src emacs-lisp
(setq ef-themes-headings
      '((0 . (1.9))
        (1 . (1.8))
        (2 . (1.7))
        (3 . (1.6))
        (4 . (1.5))
        (5 . (1.4)) ; absence of weight means `bold'
        (6 . (1.3))
        (7 . (1.2))
        (t . (1.1))))
#+end_src

I LOVE these themes from =ef-themes=:

- *Light*
  - =ef-frost=
  - =ef-light=
- *Dark*
  - =ef-cherie=
  - =ef-trio-dark=
  - =ef-winter=

I switch between them regularly, based on my mood of the day.

#+begin_src emacs-lisp
(load-theme 'ef-cherie :no-confirm)
#+end_src

=ef-themes= also provides an option for toggling between two themes, bound to the =ef-themes-toggle= function.

#+begin_src emacs-lisp
(setq ef-themes-to-toggle '(ef-cherie ef-light))
#+end_src

I consider the font to also be a component of "theme".  If it's installed, load the lovely Hack font.

#+begin_src emacs-lisp
(set-face-attribute 'default nil :family "Hack")
#+end_src

It's worth mentioning that I've tried [[https://www.nordtheme.com/ports/emacs/][nord-theme]] a couple times and found that the legibility or contrast wasn't quite good enough in some modes.  Though I still employ Nord for my terminal config in Alacritty or Kitty, where it looks /excellent/.


* Keybindings
In the unlikely event that something below is loaded incorrectly and causes initialization to stop, I like to have my basic key command loaded early, especially so that navigating to the error can happen more quickly.

Emacs has [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Key-Bindings.html][some standards]] about where user-configured keys should go.  Other non-standard modifications are marked as such.

** Keybound functions
Special utility functions that we'll bind to user keys.

#+begin_src emacs-lisp
(defun renz/--jump-section (dirname prompt extension)
  "For internal use: prompt for a file under `dirname' in the user
emacs config site with matching `extension' regexp"
  (let ((complete-dir (concat user-emacs-directory dirname "/")))
    (find-file
     (concat complete-dir
             (completing-read prompt
                              (directory-files complete-dir nil extension))))))

(defun renz/jump-configuration ()
  "Prompt for a .el file in my configuration folder, then go there."
  (interactive)
  (renz/--jump-section "config" "Elisp config files: " ".*\.el$"))

;; FIXME: should set an org-home or something like that.  Probably a common variable
;; described somewhere in the org manual
(defun renz/jump-org ()
  "Prompt for an org file in my emacs directory, then go there."
  (interactive)
  (renz/--jump-section "org" "Org files: " ".*\.org$"))

(defun renz/jump-init ()
  (interactive)
  (find-file (expand-file-name "README.org" user-emacs-directory))
  (consult-org-heading))

(defun renz/recentf-find-file ()
  "Find a recent file using the minibuffer with completion"
  (interactive)
  (recentf-mode t)
  (unless (find-file (completing-read "Find recent file: " recentf-list))
    (message "Aborting...")))

(defun renz/find-tag ()
  "Use completing-read to navigate to a tag"
  (interactive)
  (xref-find-definitions (completing-read "Find tag: " tags-completion-table)))

(defun renz/consult-grep ()
  "Live grep using `rg' if found, otherwise `grep'"
  (interactive)
  (if (executable-find "rg")
      (consult-ripgrep)
    (consult-grep)))
#+end_src

#+RESULTS:
: renz/consult-grep

** Expanded defaults

#+begin_src emacs-lisp
(global-set-key (kbd "C-M-<backspace>") 'backward-kill-sexp)
(global-set-key (kbd "C-M-h") 'backward-kill-sexp)

;; UNBINDS the suspend-frame keybinding, which is annoying on GUI.
;; Use C-x C-z if you really want to suspend the frame.
(global-set-key (kbd "C-z") #'zap-up-to-char)

;; A better version of `dabbrev'
;; https://www.masteringemacs.org/article/text-expansion-hippie-expand
;; I tend to prefer this on its own key, since I like a lot of the
;; default dabbrev behavior.
;; (global-set-key [remap dabbrev-expand] 'hippie-expand)

;; Better buffer list for C-x C-b
(global-set-key [remap list-buffers] 'ibuffer)
(global-set-key [remap switch-to-buffer] 'consult-buffer)

;; When flycheck is running (usually from a language server), bind next/previous
(with-eval-after-load 'flymake
  (define-key flymake-mode-map (kbd "M-n") 'flymake-goto-next-error)
  (define-key flymake-mode-map (kbd "M-p") 'flymake-goto-prev-error))

;; When using isearch to jump to things, use C-RET to put point on the
;; opposite side of where it would normally end up
(define-key isearch-mode-map (kbd "<C-return>")
  (defun isearch-done-opposite (&optional nopush edit)
    "End current search in the opposite side of the match."
    (interactive)
    (funcall #'isearch-done nopush edit)
    (when isearch-other-end (goto-char isearch-other-end))))
#+end_src

** C-c bindings
=C-c= <letter> is always free for users.

#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c a") #')
;; (global-set-key (kbd "C-c b") #')
(global-set-key (kbd "C-c c i") #'change-inner)
(global-set-key (kbd "C-c c o") #'change-outer)
(global-set-key (kbd "C-c d") #'renz/find-tag)
(global-set-key (kbd "C-c e") #'shell)
(global-set-key (kbd "C-c f") #'hippie-expand)
(global-set-key (kbd "C-c g") #'ffap)  ; TODO my own func that takes universal args
;; (global-set-key (kbd "C-c h") #')
;; (global-set-key (kbd "C-c i") #')
(global-set-key (kbd "C-c j") #'imenu)  ; matches major modes that use C-c C-j
(global-set-key (kbd "C-c k") #'just-one-space)
(global-set-key (kbd "C-c l d") #'flymake-show-buffer-diagnostics)
(global-set-key (kbd "C-c l f f") #'eglot-format)
(global-set-key (kbd "C-c l f b") #'eglot-format-buffer)
(global-set-key (kbd "C-c l l") #'eglot)
(global-set-key (kbd "C-c l r n") #'eglot-rename)
(global-set-key (kbd "C-c l s") #'eglot-shutdown)
(global-set-key (kbd "C-c m") #'ef-themes-toggle)
(global-set-key (kbd "C-c n") #'minimap-mode)
#+end_src

*** =C-c o= Org bindings
#+begin_src emacs-lisp
(global-set-key (kbd "C-c o a") #'org-agenda)
(global-set-key (kbd "C-c o b d") #'org-babel-detangle)
(global-set-key (kbd "C-c o b o") #'org-babel-tangle-jump-to-org)
(global-set-key (kbd "C-c o b s") #'renz/org-babel-tangle-jump-to-src)
(global-set-key (kbd "C-c o j") #'consult-org-heading)
(global-set-key (kbd "C-c o o") #'renz/jump-org)
(global-set-key (kbd "C-c o w") #'renz/org-kill-src-block)
#+end_src


#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c p") #')
;; (global-set-key (kbd "C-c q") #')
#+end_src

#+begin_src emacs-lisp
(global-set-key (kbd "C-c r") #'renz/recentf-find-file)
#+end_src

*** =C-c s= Settings

#+begin_src emacs-lisp
(global-set-key (kbd "C-c s i") #'renz/jump-init)
;; (global-set-key (kbd "C-c s k") #'renz/jump-keybindings)
;; (global-set-key (kbd "C-c s s") #'renz/jump-configuration)
#+end_src


#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c t") #')
#+end_src

*** =C-c u= Consult grep/rg

#+begin_src emacs-lisp
(global-set-key (kbd "C-c u") #'renz/consult-grep)
#+end_src

*** =C-c v=

#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c v") #')
#+end_src

#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c w") #')
#+end_src

#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c x") #')
#+end_src

*** =C-c y= Yank inner/outer

#+begin_src emacs-lisp
(global-set-key (kbd "C-c y i") #'copy-inner)
(global-set-key (kbd "C-c y o") #'copy-outer)
#+end_src

*** =C-c z=

#+begin_src emacs-lisp
;; (global-set-key (kbd "C-c z") #')
#+end_src

*** =C-c= Other bindings

#+begin_src emacs-lisp
(global-set-key (kbd "C-c ;") #'comment-line)  ; TTY-friendly
(global-set-key (kbd "C-c <DEL>") #'backward-kill-sexp)  ;; TTY-frindly
#+end_src

** Meta/Alt Modifications
#+begin_src emacs-lisp
(with-eval-after-load 'dired
  (define-key dired-mode-map (kbd "M-S-j") 'dired-goto-file))
#+end_src

** F5-F9
Like the =C-c <letter>= bindings, these are reserved for users.

#+begin_src emacs-lisp
(global-set-key (kbd "<f5>") #'compile)
(global-set-key (kbd "M-<f5>") #'recompile)
;; (global-set-key (kbd "<f6>") #')
;; (global-set-key (kbd "M-<f6>") #')
;; (global-set-key (kbd "<f7>") #')
;; (global-set-key (kbd "M-<f7>") #')
;; (global-set-key (kbd "<f8>") #')
;; (global-set-key (kbd "M-<f8>") #')
(global-set-key (kbd "<f9>") #'vterm)
(global-set-key (kbd "M-<f9>") #'eshell)
(global-set-key (kbd "S-<f9>") #'ansi-term)
(global-set-key (kbd "s-<f9>") #'shell)
#+end_src

** Nonstandard bindings

#+begin_src emacs-lisp
(when (eq system-type 'darwin)
  (with-eval-after-load 'projectile
    (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)))
#+end_src

** Super bindings
See the [[Windows][Microsoft Windows]] section for some hackery required to get these working on more platforms.

#+begin_src emacs-lisp
(global-set-key (kbd "s-s") #'save-buffer)
#+end_src


* Misc. Settings
Haven't found a home header for any of these yet.

** Fill-column
For visual lines, this adds line breaks at the fill-column value.  Especially useful for prose that is meant to be copied to other mediums, such as email or word.
#+begin_src emacs-lisp
(add-hook 'visual-line-mode-hook #'visual-fill-column-mode)
(setq-default fill-column 120)
#+end_src

** Scroll bar
I toggle this one on/off sometimes depending on how I feel lately.

#+begin_src emacs-lisp
;; Scroll bar
(scroll-bar-mode -1)
#+end_src

** Inline emojis
I tried this for a while but boy did it consume a lot of space in the =elpa/= directory!  If I go back to it I might re-install it but have to ensure I ignore the source files.

#+begin_src emacs-lisp
;; Emojis inline 👍
;; (add-hook 'after-init-hook #'global-emojify-mode)
#+end_src

** Inihibit splash screen
I can always get back to the OG GNU Spash with =C-h C-a=

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
#+end_src

** Automatically visit symlink sources

#+begin_src emacs-lisp
(setq find-file-visit-truename t)
(setq vc-follow-symlinks t)
#+end_src

** Indent with spaces

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

** Render ASCII color escape codes
For files containing color escape codes, this provides a way to render the colors in-buffer.

#+begin_src emacs-lisp
(defun renz/display-ansi-colors ()
  (interactive)
  (require 'ansi-color)
  (ansi-color-apply-on-region (point-min) (point-max)))
#+end_src

** Enable horizontal scrolling with mouse
From a helpful [[https://stackoverflow.com/a/67758169][stackoverflow answer.]]
#+begin_src emacs-lisp
(setq mouse-wheel-tilt-scroll t)
#+end_src

** Window management
I need to give the [[https://www.masteringemacs.org/article/demystifying-emacs-window-manager][article]] another read about what's going on, but it seems helpful.

#+begin_src emacs-lisp
(unless (version< emacs-version "27.1")
  (setq switch-to-buffer-obey-display-actions t))
#+end_src

** Enable up/downcase-region

#+begin_src emacs-lisp
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
#+end_src

** Automatically update buffers when contents change on disk

#+begin_src emacs-lisp
(global-auto-revert-mode)
#+end_src

** Initial frame size for GUI

#+begin_src emacs-lisp
(setq renz/frame-default-alist
      '(
        (tool-bar-lines . 0)
        (width . 180) ; chars
        (height . 60) ; lines
        (left . 125)
        (top . 125)))

(when (display-graphic-p)
  (setq initial-frame-alist renz/frame-default-alist)
  (setq default-frame-alist renz/frame-default-alist))
#+end_src

** Marginalia
Adds helpful information in the margin when using the minibuffer

#+begin_src emacs-lisp
(use-package marginalia
  :ensure t
  :config (marginalia-mode))
#+end_src

** Highlight the line point is on

#+begin_src emacs-lisp
(global-hl-line-mode)
#+end_src

** Stop stupid bell
This snippet has a special place in my heart, because it was the first two lines of elisp I wrote when first learning Emacs.

#+begin_src emacs-lisp
;; Stop stupid bell
(setq ring-bell-function 'ignore)
#+end_src

** TODO Clock in mode line
Move this to the [[Mode line][mode line]] section

#+begin_src emacs-lisp
(setq display-time-day-and-date t)
(display-time)
#+end_src

** Enable split-window dired copying

#+begin_src emacs-lisp
(setq dired-dwim-target t)
#+end_src

** Automatically create matching parens in programming modes

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook (electric-pair-mode t))
(add-hook 'prog-mode-hook (show-paren-mode t))
#+end_src

** TODO Delete whitespace on save
I would also like to have a good-looking display for trailing whitespace and leading tabs like in my Neovim setup, but its proven challenging to just narrow down to those two faces.
#+begin_src emacs-lisp
;; (add-hook 'prog-mode-hook 'whitespace-mode)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

** Don't wrap lines

#+begin_src emacs-lisp
(setq-default truncate-lines t)
(add-hook 'eshell-mode-hook (toggle-truncate-lines nil))
#+end_src

** Relative line numbers
For programming and prose/writing modes.

#+begin_src emacs-lisp
(defun renz/display-line-numbers ()
  (setq display-line-numbers 'relative))
#+end_src

Unfortunately, line numbers are displayed in the text area of the buffer, but org-modern uses the fringe to display source blocks.  [[https://www.reddit.com/r/emacs/comments/ymprwi/comment/iv5iafb/?utm_source=share&utm_medium=web2x&context=3][There's no way to display them to the left]] of the fringe, so I'm careful about only turning on line numbers in modes that I think I'll benefit from it.  It's been working pretty well in org-mode without the line numbers so far, since for each of the code blocks I can always use =C-c '= to edit in ~prog-mode~, where I /do/ get line numbers.

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'renz/display-line-numbers)
#+end_src

** Delete region when we yank on top of it
I just think that's a funny sentence, whatever we may think of it.

#+begin_src emacs-lisp
(delete-selection-mode t)
#+end_src

** Enable mouse in terminal/TTY

#+begin_src emacs-lisp
(xterm-mouse-mode 1)
#+end_src

** Compilation
As new text appears, the default behavior is for it to spill off the bottom where we can't see it.  This causes the window to follow new text as it is printed.

#+begin_src emacs-lisp
(setq compilation-scroll-output t)
#+end_src

Enable colors in the =*compilation*= buffer.  Provided by a [[https://stackoverflow.com/a/3072831/13215205][helpful stackoverflow answer]].

#+begin_src emacs-lisp
;; Enable colors in *compilation* buffer: https://stackoverflow.com/a/3072831/13215205
(defun renz/colorize-compilation-buffer ()
  "Enable colors in the *compilation* buffer."
  (require 'ansi-color)
  (let ((inhibit-read-only t))
    (ansi-color-apply-on-region (point-min) (point-max))))

(add-hook 'compilation-filter-hook 'renz/colorize-compilation-buffer)
#+end_src

** Tool bar
I usually leave the tool bar disabled
#+begin_src emacs-lisp
(tool-bar-mode -1)
#+end_src

The MENU bar, on the other hand =(menu-bar-mode)=, is very handy, and I don't think I'll ever disable it.

** TODO Show laptop battery
Move this to mode-line configuration

#+begin_src emacs-lisp
(display-battery-mode t)
#+end_src

** Ignore risky .dir-locals.el
From an [[https://emacs.stackexchange.com/a/44604][Emacs stackexchange]] answer.

#+begin_src emacs-lisp
(advice-add 'risky-local-variable-p :override #'ignore)
#+end_src

** Prefer =rg= over =grep=

#+begin_src emacs-lisp
(when (executable-find "rg")
  (setq grep-program "rg"))
#+end_src

** Make ~dired~ human-readable

#+begin_src emacs-lisp
(setq dired-listing-switches "-alFh")
(setq-default dired-hide-details-mode t)
#+end_src

** Confirm when exiting Emacs

#+begin_src emacs-lisp
(setq confirm-kill-emacs 'yes-or-no-p)
#+end_src

** Prefer ~aspell~ over ~ispell~

#+begin_src emacs-lisp
(when (executable-find "aspell")
  (setq ispell-program-name "aspell"))
#+end_src

** Smooth scrolling

#+begin_src emacs-lisp
(if (version< emacs-version "29.0")
    (pixel-scroll-mode)
  (pixel-scroll-precision-mode 1)
  (setq pixel-scroll-precision-large-scroll-height 35.0))
#+end_src

** Backup files
Keep all backup and auto-save files in a temporary folder.
#+begin_src emacs-lisp
(setq backup-directory-alist
      `(("." . temporary-file-directory))
      auto-save-file-name-transforms
      `(("." ,temporary-file-directory t)))
#+end_src

** Code syntax in Markdown
Enable syntax highlighting within code fences for markdown

#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
#+end_src

** Esup
[[https://github.com/jschaf/esup][esup]] is a tool for profiling the startup time of emacs.  This snippet is a work around of a bug where esup tries to step into the byte-compiled version of `cl-lib', and fails horribly: https://github.com/jschaf/esup/issues/85

#+begin_src emacs-lisp
(setq esup-depth 0)
#+end_src


* Minimap
I have a love-hate relationship with the minimap.  Sometimes it feels great, especially when I'm doing a mouse-heavy demo for navigation.  Other times it blocks the echo area when the window is too small and it drives me crazy.

#+begin_src emacs-lisp
(use-package minimap
  :config
  (when (display-graphic-p)
    (minimap-mode t)))
#+end_src

* Mode line

#+begin_src emacs-lisp
(setq column-number-mode t
      mode-line-in-non-selected-windows t)
#+end_src

#+RESULTS:
: t


* =eldoc=
I find it very distracting when =eldoc= suddenly pops up and consumes a large part of the screen for docstrings in python.

#+begin_src emacs-lisp
(setq eldoc-echo-area-use-multiline-p nil)
#+end_src

#+RESULTS:
: t


* Autocompletion
Emacs offers incredible depth and freedom when configuring methods that automatically complete text.  First, we set the "completion style", which is the method of assigning completion candidates to a given input string.  "flex" is the built-in "fuzzy" completion style, familiar to us from command prompts in IDEs and VSCode's command palette.

#+begin_src emacs-lisp
(setq completion-styles '(flex basic partial-completion emacs22))
#+end_src

I've found the [[https://github.com/oantolin/orderless][orderless]] completion style especially well-suited to Emacs.

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :config
  (add-to-list 'completion-styles 'orderless)
  :custom
  (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

With the /completion style/ set, we have to now configure the interfaces for /displaying/ candidates as we type.  The natural place to start would be the built-in ~*Completions*~ buffer.  First, I want candidates displayed as a single, vertical list.

#+begin_src emacs-lisp
(setq completions-format 'one-column)
#+end_src

If there is a convenient way to interact with this buffer from default key bindings, I am not aware of it.  Because of this, I set a few convenience functions for navigating to, selecting, and closing the ~*Completions*~ buffer in the case I do need to use it.

#+begin_src emacs-lisp
(defun renz/completion-accept ()
  "Expand current text to first completion result"
  (interactive)
  ;; FIXME In python REPL, if we go back inside a symbol and edit it
  ;;       to narrow the candidate list, then accept something with
  ;;       this function, the trailing text isn't erased
  (switch-to-completions)
  (choose-completion))

(defun renz/jump-completion ()
  "Jump to second completion."
  (interactive)
  (switch-to-completions)
  (next-completion 1))

(defun renz/completion-kill-completion-buffer ()
  "Close the *Completions* buffer without switching to it"
  (interactive)
  (kill-buffer "*Completions*"))
#+end_src

Much like Vim's built-in completion with the pop-up menu, I set =C-n= and =C-p= as a way to select completion candidates out of the ~*Completions*~ buffer.

#+begin_src emacs-lisp
(define-key completion-in-region-mode-map (kbd "C-n") 'renz/jump-completion)
(define-key completion-list-mode-map (kbd "C-n") 'next-completion)
(define-key completion-list-mode-map (kbd "C-p") 'previous-completion)
#+end_src

For a while, I thought keys like =RET=, =TAB=, and similar would be intuitive candidates for accepting completion candidates.  That turned out to be a problem because there's a good chance you'll mess up required functionality in shell, minibuffer, and related modes.  So, instead, I opt for the similar =C-j=.

#+begin_src emacs-lisp
(define-key completion-in-region-mode-map (kbd "C-j") 'renz/completion-accept)
(define-key completion-list-mode-map (kbd "C-j") 'choose-completion)
#+end_src

It's worth noting that the ~fido-vertical~ built-in is pretty good, but I had issues with micro-freezes in some situations.  [[https://github.com/minad/vertico][vertico]], on the other hand, has been lightning quick, and has intuitive keybindings that don't require any futzing.  /Especially/ in the case where I'm looking to tab-complete things like =C-x C-f /ssh:<thing>=.

#+begin_src emacs-lisp
(vertico-mode)
#+end_src

Emacs uses =M-TAB=, or the equivalent =C-M-i= for ~completion-at-point~.  I'd much prefer to just use the easier and more intuitive =TAB=.

#+begin_src emacs-lisp
(setq tab-always-indent 'complete)
#+end_src

** =company-mode=
This section is obsolete and not tangled into the final ~init.el~, since I don't use company anymore.  I do keep it around for historical reasons, though, in case if I ever decide to go back.

#+begin_src emacs-lisp :tangle no
;; Company causes TRAMP to hang if we look for commands too fast
(defun renz/disable-company-remote-shell ()
  (when (and (fboundp 'company-mode)
             (file-remote-p default-directory))
    (company-mode -1)))

(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'shell-mode-hook 'renz/disable-company-remote-shell)
(setq company-minimum-prefix-length 2)
(setq company-idle-delay
      (lambda () (if (company-in-string-or-comment) nil 0.0)))
(setq company-tooltip-align-annotations t)
(setq company-tooltip-flip-when-above t)
(setq company-tooltip-margin 2)
#+end_src

** =corfu=
Provides popup, suggest-as-you type like we would expect from any modern IDE.  I like =corfu= a lot, since it's philosophy is to stick as close as possible to the native Emacs internal API as possible, without inventing the whell.  In my experience, this has meant far fewer integration troubles with other packages that follow the same ideology.

#+begin_src emacs-lisp
(unless (display-graphic-p)
  (corfu-terminal-mode +1))

(defun renz/disable-corfu-remote ()
  (when (and (fboundp 'corfu-mode)
             (file-remote-p default-directory))
    (corfu-mode -1)))

(setq corfu-auto t
      corfu-auto-delay 0.0
      corfu-quit-no-match 'separator)

(global-corfu-mode)
#+end_src


* TODO Org-mode
There is a beefy startup hit from eagerly loading org-tempo, so eventually we'll have to come around and get this lazy-loaded correctly.

#+begin_src emacs-lisp :tangle no
(require 'org-tempo)
#+end_src

#+begin_src emacs-lisp
(setq org-confirm-babel-evaluate nil)
(setq org-edit-src-content-indentation 0)
#+end_src

I use =consult-org-heading= for jumping between headers now, so I no longer tangle this line into my config.

#+begin_src emacs-lisp :tangle no
(setq org-goto-interface 'outline-path-completion)
#+end_src

When displaying images, I usually like to resize them to a comfortable width, which the following enables.

#+begin_src emacs-lisp
(setq org-image-actual-width nil)
#+end_src

I often want to kill and paste entire ~src~ blocks at a time.  As far as I know, there's no built-in command for that, so I just made my own.

#+begin_src emacs-lisp
(defun renz/org-kill-src-block ()
  "Kill the src block around point, if applicable."
  (interactive)
  (org-babel-remove-result)
  (org-mark-element)
  (kill-region nil nil t))
#+end_src

I also use ~org-mode~ for writing [[https://robbmann.io/posts][my blog.]]  With a little help from [[https://willschenk.com/articles/2019/using_org_mode_in_hugo/][an article]] we have exporting to Hugo-specific markdown.  Without the export, Hugo can read Org files /okay-ish/, but you wind up missing some nice QoL features, like header links.

#+begin_src emacs-lisp
(with-eval-after-load 'ox
  (require 'ox-hugo))
#+end_src

Now we configure ~org-mode~ itself.  For a while I was trying =(setq org-startup-indented t)= t get indentation under each header, but this was interfering with the beautification features from ~org-modern~.  Preferring the latter over the former, I've removed the =org-startup-indented= call.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (add-hook 'org-mode-hook #'visual-line-mode)

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (sql . t)
     (shell . t)))

  ;; Enable asynchronous execution of src blocks
  (when (package-installed-p 'ob-async)
    (require 'ob-async)
    (add-hook 'ob-async-pre-execute-src-block-hook
              #'(lambda ()
                  (require 'ob-sql-mode)
                  (require 'hive2))))
  )

(setq ob-async-no-async-languages-alist '("python"))
(setq org-html-htmlize-output-type 'css)

;; For navigating to tangled src blocks
;; https://emacs.stackexchange.com/a/69591
(defun renz/org-babel-tangle-jump-to-src ()
  "The opposite of `org-babel-tangle-jump-to-org'.
Jumps at tangled code from org src block."
  (interactive)
  (if (org-in-src-block-p)
      (let* ((header (car (org-babel-tangle-single-block 1 'only-this-block)))
             (tangle (car header))
             (lang (caadr header))
             (buffer (nth 2 (cadr header)))
             (org-id (nth 3 (cadr header)))
             (source-name (nth 4 (cadr header)))
             (search-comment (org-fill-template
                              org-babel-tangle-comment-format-beg
                              `(("link" . ,org-id) ("source-name" . ,source-name))))
             (file (expand-file-name
                    (org-babel-effective-tangled-filename buffer lang tangle))))
        (if (not (file-exists-p file))
            (message "File does not exist. 'org-babel-tangle' first to create file.")
          (find-file file)
          (beginning-of-buffer)
          (search-forward search-comment)))
    (message "Cannot jump to tangled file because point is not at org src block.")))

;; TODO states
(setq org-todo-keywords '((sequence "TODO" "DEAD" "DONE")))
#+end_src

#+RESULTS:
| sequence | TODO | DEAD | DONE |

#+begin_src emacs-lisp
(setq org-agenda-files '("~/.emacs.d/org/work.org")
      org-hugo-front-matter-format "yaml")
#+end_src

** Org Roam
#+begin_src emacs-lisp :tangle no
(setq org-roam-directory (file-truename "~/.emacs.d/org/org-roam")

Consider the below for Windows only
(setq org-roam-database-connector 'sqlite3)

(org-roam-db-autosync-mode)
#+end_src

** Displaying remote images
Leaving this one out for a while too, as I'm not yet sure how useful it will be.  Taken from a blog post related to an issue I had running remote python from a local Org file: http://kychoi.org/blog/2014/11/02/Org-Display-Inline-Remote-Images

#+begin_src emacs-lisp :tangle no
(defun org-display-inline-images (&optional include-linked refresh beg end)
  "Display inline images.

An inline image is a link which follows either of these
conventions:

  1. Its path is a file with an extension matching return value
     from `image-file-name-regexp' and it has no contents.

  2. Its description consists in a single link of the previous
     type.

When optional argument INCLUDE-LINKED is non-nil, also links with
a text description part will be inlined.  This can be nice for
a quick look at those images, but it does not reflect what
exported files will look like.

When optional argument REFRESH is non-nil, refresh existing
images between BEG and END.  This will create new image displays
only if necessary.  BEG and END default to the buffer
boundaries."
  (interactive "P")
  (when (display-graphic-p)
    (unless refresh
      (org-remove-inline-images)
      (when (fboundp 'clear-image-cache) (clear-image-cache)))
    (org-with-wide-buffer
     (goto-char (or beg (point-min)))
     (let ((case-fold-search t)
	   (file-extension-re (org-image-file-name-regexp)))
       (while (re-search-forward "[][]\\[\\(?:file\\|[./~]\\)" end t)
	 (let ((link (save-match-data (org-element-context))))
	   ;; Check if we're at an inline image.
	   (when (and (equal (org-element-property :type link) "file")
		      (or include-linked
			  (not (org-element-property :contents-begin link)))
		      (let ((parent (org-element-property :parent link)))
			(or (not (eq (org-element-type parent) 'link))
			    (not (cdr (org-element-contents parent)))))
		      (org-string-match-p file-extension-re
					  (org-element-property :path link)))
	     (let ((file (substitute-in-file-name (expand-file-name (org-element-property :path link)))))
	       (when (file-exists-p file)
		 (let ((width
			;; Apply `org-image-actual-width' specifications.
			(cond
			 ((not (image-type-available-p 'imagemagick)) nil)
			 ((eq org-image-actual-width t) nil)
			 ((listp org-image-actual-width)
			  (or
			   ;; First try to find a width among
			   ;; attributes associated to the paragraph
			   ;; containing link.
			   (let ((paragraph
				  (let ((e link))
				    (while (and (setq e (org-element-property
							 :parent e))
						(not (eq (org-element-type e)
							 'paragraph))))
				    e)))
			     (when paragraph
			       (save-excursion
				 (goto-char (org-element-property :begin paragraph))
				   (when
				       (re-search-forward
					"^[ \t]*#\\+attr_.*?: +.*?:width +\\(\\S-+\\)"
					(org-element-property
					 :post-affiliated paragraph)
					t)
				     (string-to-number (match-string 1))))))
			   ;; Otherwise, fall-back to provided number.
			   (car org-image-actual-width)))
			 ((numberp org-image-actual-width)
			  org-image-actual-width)))
		       (old (get-char-property-and-overlay
			     (org-element-property :begin link)
			     'org-image-overlay)))
		   (if (and (car-safe old) refresh)
		       (image-refresh (overlay-get (cdr old) 'display))
		     (let ((image
			    (create-image (if (org-file-remote-p file)
					      (let* ((tramp-tmpdir (concat
								    (if (featurep 'xemacs)
									(temp-directory)
								      temporary-file-directory)
								    "/tramp"
								    (file-name-directory (expand-file-name file))))
						     (newname (concat
							       tramp-tmpdir
							       (file-name-nondirectory (expand-file-name file)))))
						(make-directory tramp-tmpdir t)
						(if (file-newer-than-file-p file newname)
						    (copy-file file newname t t))
						newname)
					    file)
					  (and width 'imagemagick)
					  nil
					  :width width)))
		       (when image
			 (let* ((link
				 ;; If inline image is the description
				 ;; of another link, be sure to
				 ;; consider the latter as the one to
				 ;; apply the overlay on.
				 (let ((parent
					(org-element-property :parent link)))
				   (if (eq (org-element-type parent) 'link)
				       parent
				     link)))
				(ov (make-overlay
				     (org-element-property :begin link)
				     (progn
				       (goto-char
					(org-element-property :end link))
				       (skip-chars-backward " \t")
				       (point)))))
			   (overlay-put ov 'display image)
			   (overlay-put ov 'face 'default)
			   (overlay-put ov 'org-image-overlay t)
			   (overlay-put
			    ov 'modification-hooks
			    (list 'org-display-inline-remove-overlay))
			   (push ov org-inline-image-overlays)))))))))))))))
#+end_src


** =org-modern=
From the lovely minad: https://github.com/minad/org-modern

#+begin_src emacs-lisp
;; TODO: move this to the misc./ window settings
;; add frame borders and window dividers
(modify-all-frames-parameters
 '((right-divider-width . 40)
   (internal-border-width . 40)))
(dolist (face '(window-divider
                window-divider-first-pixel
                window-divider-last-pixel))
  (face-spec-reset-face face)
  (set-face-foreground face (face-attribute 'default :background)))
(set-face-background 'fringe (face-attribute 'default :background))

(setq
 ;; edit settings
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-special-ctrl-a/e t
 org-insert-heading-respect-content t

 ;; Org styling, hide markup etc.
 org-hide-emphasis-markers t
 org-pretty-entities t
 org-ellipsis "…"

 ;; Agenda styling
 org-agenda-tags-column 0
 org-agenda-block-separator ?─
 org-agenda-time-grid
 '((daily today require-timed)
   (800 1000 1200 1400 1600 1800 2000)
   " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
 org-agenda-current-time-string
 "⭠ now ─────────────────────────────────────────────────")

(global-org-modern-mode)
#+end_src


* SQL

#+begin_src emacs-lisp
(defun renz/sql-mode-hook ()
  ;; (setq indent-line-function 'renz/sql-indent)
  (setq tab-width 4)
  (setq sqlformat-command 'sql-formatter)
  (setq sqlind-basic-offset 4)
  ;; (setq electric-indent-inhibit t)
  )

(add-hook 'sql-mode-hook #'renz/sql-mode-hook)
(add-to-list 'auto-mode-alist '("\\.hql" . sql-mode))
(add-hook 'sql-mode-hook 'sqlup-mode)
(add-hook 'sql-mode-hook 'sqlind-minor-mode)
(add-hook 'sql-interactive-mode-hook 'sqlup-mode)

(with-eval-after-load 'sql
  (require 'hive2)
  (require 'ob-sql-mode)
  (require 'sqlformat)
  (require 'sqlup-mode)
  (require 'sql-indent)

  (defvar renz/sql-indentation-offsets-alist
    `((select-clause 0)
      (insert-clause 0)
      (delete-clause 0)
      (update-clause 0)
      ,@sqlind-default-indentation-offsets-alist))

  (add-hook 'sqlind-minor-mode-hook
            (lambda ()
              (setq sqlind-indentation-offsets-alist
                    renz/sql-indentation-offsets-alist)))
  )
#+end_src


* Python
#+begin_src emacs-lisp
;; Example error from pyright
;; --------------------------
;; /home/robb/tmp/errors.py/
;;   /home/robb/tmp/errors.py:1:1 - error: "foo" is not defined (reportUndefinedVariable)
;;   /home/robb/tmp/errors.py:1:1 - warning: Expression value is unused (reportUnusedExpression)
;;   /home/robb/tmp/errors.py:4:12 - error: Operator "+" not supported for types "str" and "Literal[1]"
;;     Operator "+" not supported for types "str" and "Literal[1]" (reportGeneralTypeIssues)
;; 2 errors, 1 warning, 0 informations
(with-eval-after-load 'compile
  (add-to-list 'compilation-error-regexp-alist-alist
               ;; It would be nice if we could also capture the
               ;; \\(error\\|warning\\) part as "KIND", but I got messed
               ;; up on it
               '(pyright "^[[:blank:]]+\\(.+\\):\\([0-9]+\\):\\([0-9]+\\).*$" 1 2 3))
  (add-to-list 'compilation-error-regexp-alist 'pyright))

;; Extra check commands for C-c C-v
(with-eval-after-load 'python
  (if (executable-find "mypy")
      (setq python-check-command "mypy"))
  (if (executable-find "pyright")
      (setq python-check-command "pyright")))

;; I ran into something similar to this on Windows:
;; https://github.com/jorgenschaefer/elpy/issues/733
;;
;; The culprit was "App Execution Aliases" with python and python3
;; redirecting to the windows store. Using:
;;
;;     winkey -> Manage app execution aliases -> uncheck python and python3
;;
;; fixed it.

;; Also on Windows - a `pip install` of `pyreadline3' is required to
;; make tab-completion work at all. It provides the `readline' import
;; symbol.

;; Virtualenvs - require .dir-locals.el to have e.g.:
;;   ((python-mode . ((python-shell-virtualenv-root . "/path/to/my/.venv"))))
;; However, this only operates on `run-python' shells.
;;
;; `pyvenv' solves the otherwise very annoying problem of getting
;; external tools like `compile' and `eshell' to also use our virtual
;; environment's python.  I may still use .dir-locals.el to set things
;; like the python-check-command on a per-project basis, though.
(when (package-installed-p 'pyvenv)
  (pyvenv-mode)
  ;; (add-hook 'pyvenv-post-activate-hooks 'pyvenv-restart-python)
  ;; (pyvenv-tracking-mode)
  ;; (setenv "WORKON_HOME" "~/.conda/envs")
  )

;; Enable semantic mode for more intelligent code parsing
;; https://www.gnu.org/software/emacs/manual/html_node/semantic/Semantic-mode.html
;; (add-hook 'python-mode-hook 'semantic-mode)

;; Don't mark the check command and virtualenv variables as unsafe
(put 'python-check-command 'safe-local-variable #'stringp)
(put 'python-shell-virtualenv-root 'safe-local-variable #'stringp)

;; (add-hook 'python-mode-hook 'eglot-ensure)
#+end_src


* Microsoft Windows

#+begin_src emacs-lisp
(when (eq system-type 'windows-nt)
  ;; Set a better font on Windows
  (set-face-attribute 'default nil :font "Hack NF-12")
  ;; Alternate ispell when we've got msys on Windows
  (setq ispell-program-name "c:/msys64/usr/bin/aspell.exe")
  ;; Set default shell to pwsh
  (setq explicit-shell-file-name "pwsh")
  ;; Enable use of Winkey as super
  (setq w32-pass-lwindow-to-system nil)
  (setq w32-lwindow-modifier 'super) ; Left Windows key
  (setq w32-pass-rwindow-to-system nil)
  (setq w32-rwindow-modifier 'super) ; Right Windows key
  ;; If we want to use a hotkey, we have to also register each
  ;; combination specifically, like this:
  (w32-register-hot-key [s-a])
  (w32-register-hot-key [s-b])
  (w32-register-hot-key [s-c])
  (w32-register-hot-key [s-d])
  (w32-register-hot-key [s-e])
  (w32-register-hot-key [s-f])
  (w32-register-hot-key [s-g])
  (w32-register-hot-key [s-h])
  (w32-register-hot-key [s-i])
  (w32-register-hot-key [s-j])
  (w32-register-hot-key [s-k])
  ;; s-l can NEVER be registered as a key combination, since Windows
  ;; handles it at a much lower level.
  ;; (w32-register-hot-key [s-l])
  (w32-register-hot-key [s-m])
  (w32-register-hot-key [s-n])
  (w32-register-hot-key [s-o])
  (w32-register-hot-key [s-p])
  (w32-register-hot-key [s-q])
  (w32-register-hot-key [s-r])
  (w32-register-hot-key [s-s])
  (w32-register-hot-key [s-t])
  (w32-register-hot-key [s-u])
  (w32-register-hot-key [s-v])
  (w32-register-hot-key [s-w])
  (w32-register-hot-key [s-x])
  (w32-register-hot-key [s-y])
  (w32-register-hot-key [s-z]))
#+end_src


* macOS

#+begin_src emacs-lisp
(when (eq system-type 'darwin)
  ;; Uncomment this if we can't install Hack Nerd font
  ;; (set-face-attribute 'default nil :font "Menlo-14")
  (set-face-attribute 'default nil :font "Hack Nerd Font Mono-13")
  (exec-path-from-shell-initialize)

  ;; Better terminal emulation
  (require 'vterm)
  (add-hook 'vterm-mode-hook (lambda () (setq-local global-hl-line-mode nil)))

  (unless (version< emacs-version "29.0"))
    (setq pixel-scroll-precision-use-momentum t)
  )
#+end_src


* Linux
#+begin_src emacs-lisp
(when (eq system-type 'gnu/linux)
  (set-face-attribute 'default nil :font "Hack Nerd Font Mono-11")
  ;; (exec-path-from-shell-initialize)
  )
#+end_src

* Tramp
#+begin_src emacs-lisp
(setq vc-handled-backends '(Git))
(setq remote-file-name-inhibit-locks t)
(setq tramp-inline-compress-start-size 1000)
(setq tramp-copy-size-limit 10000)
(setq tramp-verbose 1)

;; Without this line, we get the "Forbidden reentrant call of Tramp" bug: https://github.com/joaotavora/eglot/issues/859
(setq tramp-use-ssh-controlmaster-options nil)

;; Enable .dir-locals.el for remote files
;; REMINDME: This can case a HUGE slowdown when doing things like `project-find-file'
;; (setq enable-remote-dir-locals t)

(with-eval-after-load 'tramp
  (add-to-list 'tramp-remote-path "~/.local/bin")
  (add-to-list 'tramp-remote-path "~/.conda/envs/robbmann/bin")
  ;; (remove-hook 'find-file-hook 'vc-find-file-hook)
  ;; (add-to-list 'tramp-connection-properties
  ;;              (list (regexp-quote "/ssh:7p")
  ;;                    "remote-shell" "/usr/bin/ksh"))
  )
#+end_src

[[https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html][Disabling VC]] /does/ seem to speed things up a little, but it's not an acceptable thing to put in, since I so frequently use VC over tramp.

#+begin_src emacs-lisp :tangle no
(setq vc-ignore-dir-regexp
      (format "\\(%s\\)\\|\\(%s\\)"
              vc-ignore-dir-regexp
              tramp-file-name-regexp))
#+end_src

Additionally, these came up as potential options [[https://github.com/doomemacs/doomemacs/issues/3909][from the doom-emacs issues]].
#+begin_src emacs-lisp :tangle no
(setq tramp-inline-compress-start-size 1000)
(setq tramp-copy-size-limit 10000)
(setq vc-handled-backends '(Git))
(setq tramp-verbose 1)
(setq tramp-default-method "scp")
(setq tramp-use-ssh-controlmaster-options nil)
(setq projectile--mode-line "Projectile")
(setq tramp-verbose 1)
#+end_src

I often need to set these in ~/.ssh/config for TRAMP to speed up

#+begin_example
Host *
     ControlMaster auto
     ControlPath ~/.ssh/master-%h:%p
     ControlPersist 10m
     ForwardAgent yes
     ServerAliveInterval 60
#+end_example


* LSP
Another section that's almost totally obsolete, but kept in case I need references to it.  Since =eglot= will be a built-in package for future emacs, I'm going to stick to it.

#+begin_src emacs-lisp :tangle no
(require 'lsp-mode)

(setq lsp-keymap-prefix "s-p")
(lsp-register-client
    (make-lsp-client :new-connection (lsp-tramp-connection "pylsp")
                     :major-modes '(python-mode)
                     :remote? t
                     :server-id 'pylsp-remote))

(lsp-register-client
    (make-lsp-client :new-connection (lsp-tramp-connection '("pyright-langserver" "--stdio"))
                     :major-modes '(python-mode)
                     :remote? t
                     :server-id 'pyright-remote))

(defun lsp-tramp-connection (local-command &optional generate-error-file-fn)
    "Create LSP stdio connection named name.
LOCAL-COMMAND is either list of strings, string or function which
returns the command to execute."
    (defvar tramp-connection-properties)
    ;; Force a direct asynchronous process.
    (when (file-remote-p default-directory)
      (add-to-list 'tramp-connection-properties
                   (list (regexp-quote (file-remote-p default-directory))
                         "direct-async-process" t)))
    (list :connect (lambda (filter sentinel name environment-fn)
                     (let* ((final-command (lsp-resolve-final-function
                                            local-command))
                            (_stderr (or (when generate-error-file-fn
                                           (funcall generate-error-file-fn name))
                                         (format "/tmp/%s-%s-stderr" name
                                                 (cl-incf lsp--stderr-index))))
                            (process-name (generate-new-buffer-name name))
                            (process-environment
                             (lsp--compute-process-environment environment-fn))
                            (proc (make-process
                                   :name process-name
                                   :buffer (format "*%s*" process-name)
                                   :command final-command
                                   :connection-type 'pipe
                                   :coding 'no-conversion
                                   :noquery t
                                   :filter filter
                                   :sentinel sentinel
                                   :file-handler t)))
                       (cons proc proc)))
          :test? (lambda () (-> local-command lsp-resolve-final-function
                           lsp-server-present?))))

(setq lsp-completion-provider :none)

(defun renz/corfu-lsp-setup ()
  (setq-local completion-styles '(flex basic partial-completion emacs22)
              completion-category-defaults nil))

(add-hook 'lsp-mode-hook #'renz/corfu-lsp-setup)

#+end_src


* TreeSitter
#+begin_src emacs-lisp
;; TODO: Convert this to use-package
(require 'tree-sitter)
(require 'tree-sitter-langs)
(global-tree-sitter-mode)
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)
#+end_src

* Footer
Thank you for reading 'till the end or for being interested on how to end an Emacs package.  So that's it, let's gracefully finish tangling everything:

#+begin_src emacs-lisp :comments no
(provide 'init.el)
;;; init.el ends here
#+end_src
