;;; caddyfile-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from caddyfile-mode.el

(autoload 'caddyfile-mode "caddyfile-mode" "\
Major mode for editing Caddy configuration files.

(fn)" t)
(add-to-list 'auto-mode-alist '("Caddyfile\\'" . caddyfile-mode))
(register-definition-prefixes "caddyfile-mode" '("caddyfile-"))

;;; End of scraped data

(provide 'caddyfile-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; caddyfile-mode-autoloads.el ends here
