;;; heex-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from heex-ts-mode.el

(add-to-list 'auto-mode-alist '("\\.[hl]?eex\\'" . heex-ts-mode))
(autoload 'heex-ts-mode "heex-ts-mode" "\
Major mode for editing Heex, powered by tree-sitter.

(fn)" t)
(register-definition-prefixes "heex-ts-mode" '("heex-ts-"))

;;; End of scraped data

(provide 'heex-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; heex-ts-mode-autoloads.el ends here
