;;; llm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from llm.el

(register-definition-prefixes "llm" '("llm-"))


;;; Generated autoloads from llm-claude.el

(register-definition-prefixes "llm-claude" '("llm-claude--"))


;;; Generated autoloads from llm-deepseek.el

(register-definition-prefixes "llm-deepseek" '("llm-deepseek--get-partial-chat-response"))


;;; Generated autoloads from llm-gemini.el

(register-definition-prefixes "llm-gemini" '("llm-gemini--"))


;;; Generated autoloads from llm-llamacpp.el

(register-definition-prefixes "llm-llamacpp" '("llm-llamacpp-"))


;;; Generated autoloads from llm-models.el

(register-definition-prefixes "llm-models" '("llm-models"))


;;; Generated autoloads from llm-ollama.el

(register-definition-prefixes "llm-ollama" '("llm-ollama-"))


;;; Generated autoloads from llm-openai.el

(register-definition-prefixes "llm-openai" '("llm-"))


;;; Generated autoloads from llm-prompt.el

(register-definition-prefixes "llm-prompt" '("llm-"))


;;; Generated autoloads from llm-provider-utils.el

(register-definition-prefixes "llm-provider-utils" '("llm-provider-utils-"))


;;; Generated autoloads from llm-request-plz.el

(register-definition-prefixes "llm-request-plz" '("llm-request-"))


;;; Generated autoloads from llm-tester.el

(register-definition-prefixes "llm-tester" '("llm-tester-"))


;;; Generated autoloads from llm-vertex.el

(register-definition-prefixes "llm-vertex" '("llm-vertex-"))

;;; End of scraped data

(provide 'llm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; llm-autoloads.el ends here
