;;; clojure-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from clojure-ts-mode.el

(autoload 'clojure-ts-mode "clojure-ts-mode" "\
Major mode for editing Clojure code.

\\{clojure-ts-mode-map}

(fn)" t)
(autoload 'clojurescript-ts-mode "clojure-ts-mode" "\
Major mode for editing ClojureScript code.

\\{clojurescript-ts-mode-map}

(fn)" t)
(autoload 'clojurec-ts-mode "clojure-ts-mode" "\
Major mode for editing ClojureC code.

\\{clojurec-ts-mode-map}

(fn)" t)
(autoload 'clojure-dart-ts-mode "clojure-ts-mode" "\
Major mode for editing Clojure Dart code.

\\{clojure-dart-ts-mode-map}

(fn)" t)
(autoload 'clojure-jank-ts-mode "clojure-ts-mode" "\
Major mode for editing Jank code.

\\{clojure-jank-ts-mode-map}

(fn)" t)
(register-definition-prefixes "clojure-ts-mode" '("clojure"))

;;; End of scraped data

(provide 'clojure-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; clojure-ts-mode-autoloads.el ends here
