* Keys
** =C-h R= for ~info-display-manual~
** =C-x C-0= to interactively change text size of a buffer
** Reposition cursor
*** =M-r= cycle
*** =M-0 M-r= top
*** =M-- M-r= bottom
** =C-;= in flyspell mode to correct last misspelling
** =M-?= to use ~xref-find-references~
** =M-.= to use ~xref-find-definitions~
** =C-h-.= to use ~eldoc-doc-buffer~ for viewing documentation
** =C-x C-j= to open dired to the folder current buffer is referencing
** =C-x C-q= to make dired editable for easy renaming of filesq
** =M-s o= new occur buffer with search term and press e to edit directly within the occur buffer
*** =C-u N M-s o= to show N lines above/below search results
** =M-s w= search for word
** =M-e= in isearch switch to minibuffer
** =M-@= ~mark-word~
** =C-x C-o= deletes all but one consecutive blank lines
** =M-$= check spelling

* Functions
** Check if a file is remote using =(file-remote-p default-directory)=
** ~studlify-region~ to add sarcasm
** ~just-one-space~ to kill all whitespace around point, use with prefix to kill newlines too

* External
** =find . -name "*.py" -print | etags -= to re-generate project tags
** Getting homebrew without sudo: https://superuser.com/a/1603383
  #+begin_example
  mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
  #+end_example

* Python
** Install language servers to their own venv, then /use/ them from venv
*** =python-lsp-server=
pipx is best:

#+begin_src sh
python3 -m pip install --user pipx
pipx install python-lsp-server
pipx runpip python-lsp-server[flake8] install pylsp-mypy python-lsp-black types-requests pandas-stubs sqlalchemy-stubs
#+end_src

It's unclear whether the types are better installed to the venv or to
the lsp-server venv.  It also seems likely that we'll get version
clashes between the stubs and the actually installed library.  If
that's the case, this seems ... difficult to manage.

*** =pyright-langserver=
Here, the easiest solution I've found is to also use =npm install -g=
or =pipx install pyright=, but then use a =pyrightconfig.json= in the
project root that points to the virtual environment:

#+begin_src javascript
{
    "venv": ".venv"
}
#+end_src

The path can be either relative or absolute, but the former is easier
to port to other users.

Note that we can't use ~~~:
#+begin_src js
    "venvPath": "~/miniconda3/envs",  # illegal!
#+end_src

Also, when =pyrightconfig.json= is not at the top level of the
project, it wasn't detected.  That is:

#+begin_example
.emacs.d/
|- pyrightconfig.json
`-python/
  `myguy.py
#+end_example

is the only acceptable setup.  Trying to set it up as
=.emacs.d/python/pyrightconfig.json= instead left it undetected.
